return {}
-- return {
--   {
--     "iamcco/markdown-preview.nvim",
--     build = "cd app && npm install",
--     ft = "markdown",
--     pinned = true,
--     keys = {
--       {
--         "<leader>gm",
--         "<cmd>MarkdownPreviewToggle<cr>",
--         desc = "Markdown Preview",
--         ft = "markdown",
--       },
--     },
--   },
-- }
